//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreWebForms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorList { get; set; }
        public string Isbn { get; set; }
        public System.DateTime PublishingDate { get; set; }
        public int PublisherId { get; set; }
        public int CategoryId { get; set; }
        public int PageCount { get; set; }
        public double Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
